### PR TITLE
Added an option to remove missing keys

### PR DESCRIPTION
**Pull request by filip-nifti**
I added an option that will remove keys that are not present when you run the localize command.
This was mentioned in the #26 and @amiranagram self-assigned it. I was in need of the feature so i impemented it. Hopefully it can be of use to someone else :)

### Contribution rules
- [x] Follow the PSR-2 Coding Standard]
- [x] Add tests!
- [x] Document any change in behaviour 
- [x] Consider our release cycle
- [x] One pull request per feature 
- [x] Send coherent history

### CODE REVIEW

**Comment by amiranagram** [comment]
Thank you for your PR. Can you checkout the failing tests?

**Comment by filip-nifti** [comment]
Will do!

**Comment by filip-nifti** [comment]
There are 10 errors but that seems to be in the orchestra/testbench-core package.
The 1 failure seems to be in the testcase.php which is because of:
`Call to undefined method Illuminate\Container\Container::resourcePath()`.
I haven't modified that file at all and cant think of a way how my changes affected that.
When i googled it, it seemed to be common that the solution is to extend the testcase using 
`Tests\TestCase` Instead of  `PHPUnit\Framework\TestCase` Which the orchestra/testbench-core package uses. 
Do you have any leads or thoughts on this?

**Comment by amiranagram** [comment]
OK, I managed to track down the error and fix it. Thank you for your contribution!

**Pull request merged**
